const teamCaptains = {
  "Algeria": ["Aïssa Mandi"],
  "Argentina": ["Lionel Messi"],
  "Australia": ["Matthew Ryan"],
  "Austria": ["David Alaba"],
  "Belgio": ["Youri Tielemans"],
  "Bosnia ed Erzegovina": ["Edin Dzeko"],
  "Brasile": ["Marquinhos"],
  "Canada": ["Alphonso Davies"],
  "Capo Verde": ["Ryan Mendes"],
  "Colombia": ["James Rodríguez"],
  "Corea del Sud": ["Song Heung-Min"],
  "Costa d'Avorio": ["Franck Kessié"],
  "Croazia": ["Luka Modric"],
  "Curacao": ["Leandro Bacuna"],
  "Ecuador": ["Enner Valencia"],
  "Francia": ["Kylian Mbappé"],
  "Germania": ["Joshua Kimmich"],
  "Giordania": ["Ehsan Haddad"],
  "Haiti": ["Johnny Placide"],
  "Inghilterra": ["Harry Kane"],
  "Marocco": ["Achraf Hakimi"],
  "Nuova Zelanda": ["Chris Wood"],
  "Olanda": ["Virgil van Dijk"],
  "Panama": ["Aníbal Godoy"],
  "Paraguay": ["Gustavo Gómez"],
  "Portogallo": ["Cristiano Ronaldo"],
  "Qatar": ["Hassan Al Haydos"],
  "RD Congo": ["Chancel Mbemba"],
  "Repubblica Ceca": ["Ladislav Krejci"],
  "Scozia": ["Andy Robertson"],
  "Senegal": ["Kalidou Koulibaly"],
  "Stati Uniti": ["Tim Ream"],
  "Svezia": ["Viktor Lindelöf"],
  "Svizzera": ["Gran Xhaka"],
  "Turchia": ["Hakan Calhanoglu"],
  "Uruguay": ["José María Giménez"],
  "Uzbekistan": ["Eldor Shomurodov"]
};
