const penaltyTakers = {
  "Algeria": ["Mahrez", "Bentaleb", "Amoura"],
  "Arabia Saudita": ["Al-Dawsari", "Al-Buraikan", "Al-Juwayr"],
  "Argentina": ["Messi", "Otamendi", "Alvarez"],
  "Australia": ["Hrustic", "Irankunda", "Yengi"],
  "Austria": ["Arnautovic", "Sabitzer", "Baumgartner"],
  "Belgio": ["De Bruyne", "Lukaku", "Tielemans"],
  "Bosnia ed Erzegovina": ["Dzeko", "Demirovic", "Tabakovic"],
  "Brasile": ["Neymar", "Raphinha", "Vinicius Jr"],
  "Canada": ["J. David", "P. David", "Larin"],
  "Capo Verde": ["Mendes", "Rodriguez", "Livramento"],
  "Colombia": ["James Rodriguez", "Diaz", "Quintero"],
  "Corea del Sud": ["Heung-Min Son", "Hee-Chan Hwang", "Lee Kang-In"],
  "Costa d'Avorio": ["Kessie", "Pepe", "Sangare"],
  "Curacao": ["L. Bacuna", "J. Bacuna", "Locadia"],
  "Croazia": ["Modric", "Perisic", "Kramaric"],
  "Ecuador": ["E. Valencia", "J. Caicedo", "Paez"],
  "Egitto": ["Salah", "Marmoush", "Saber"],
  "Francia": ["Mbappe", "Dembele", "T. Hernandez"],
  "Germania": ["Havertz", "Kimmich", "Wirtz"],
  "Ghana": ["J. Ayew", "Semenyo", "I. Williams"],
  "Giappone": ["Ueda", "Kamada", "K. Nakamura"],
  "Giordania": ["A. Olwan", "Tamari", "Shararh"],
  "Haiti": ["Nazon", "Pierrot", "Isidor"],
  "Inghilterra": ["Kane", "Rashford", "Saka"],
  "Iran": ["Taremi", "Hosseinzadeh", "Jahanbakhsh"],
  "Iraq": ["Hussein", "Al-Ammari", "M. Ali"],
  "Marocco": ["Brahim Diaz", "Hakimi", "Rahimi"],
  "Messico": ["Jimenez", "Pineda", "S. Gimenez"],
  "Norvegia": ["Haaland", "Sorloth", "Odegaard"],
  "Nuova Zelanda": ["Wood", "Waine", "Singh"],
  "Olanda": ["Depay", "Gakpo", "Malen"],
  "Panama": ["Waterman", "Davis", "Diaz"],
  "Paraguay": ["Enciso", "Sanabria", "Almiron"],
  "Portogallo": ["Cristiano Ronaldo", "Bruno Fernandes", "Vitinha"],
  "Qatar": ["Afif", "A. Ali", "Miguel"],
  "Repubblica Ceca": ["Schick", "Soucek", "Chory"],
  "RD Congo": ["Wissa", "Kakuta", "Bakambu"],
  "Scozia": ["McTominay", "McGinn", "Christie"],
  "Senegal": ["Mane", "Jackson", "I. Sarr"],
  "Spagna": ["Ferran Torres", "Rodri", "Yamal"],
  "Stati Uniti": ["Pulisic", "Balogun", "Pepi"],
  "Sudafrica": ["Foster", "Mokoena", "Appollis"],
  "Svezia": ["Gyokeres", "Isak", "Sema"],
  "Svizzera": ["Xhaka", "Embolo", "Amdouni"],
  "Tunisia": ["Gharbi", "Abdi", "Achouri"],
  "Turchia": ["Calhanoglu", "Akturkoglu", "Yildiz"],
  "Uruguay": ["Valverde", "Nunez", "Zalazar"],
  "Uzbekistan": ["Shomurodov", "Mozgovoy", "Sergeev"],
};
