const psychologicalFactors = {
  "Argentina": {
    motivazione: 92,
    pressione: 88,
    momentoEmotivo: 10,
    notaPsicologica: "Due vittorie, cinque gol di Messi e qualificazione anticipata: fiducia massima, pur con aspettative sempre molto elevate.",
  },
  "Francia": {
    motivazione: 90,
    pressione: 85,
    momentoEmotivo: 9,
    notaPsicologica: "Due vittorie, sei gol segnati e qualificazione anticipata confermano profondita e mentalita vincente.",
  },
  "Brasile": {
    motivazione: 95,
    pressione: 95,
    momentoEmotivo: -2,
    notaPsicologica: "Ossessione nazionale per il sesto Mondiale, ma ogni passo falso genera critiche enormi.",
  },
  "Inghilterra": {
    motivazione: 94,
    pressione: 98,
    momentoEmotivo: 0,
    notaPsicologica: "Il 0-0 con il Ghana non compromette il percorso, ma riporta addosso il peso delle aspettative e della pressione mediatica.",
  },
  "Spagna": {
    motivazione: 89,
    pressione: 82,
    momentoEmotivo: 5,
    notaPsicologica: "Il 4-0 sull'Arabia Saudita cancella parte delle scorie dello 0-0 iniziale e restituisce fiducia alla nuova generazione.",
  },
  "Portogallo": {
    motivazione: 92,
    pressione: 92,
    momentoEmotivo: 6,
    notaPsicologica: "Il 5-0 sull'Uzbekistan libera energia dopo il pari col Congo e rilancia la centralita emotiva di Cristiano Ronaldo.",
  },
  "Germania": {
    motivazione: 91,
    pressione: 90,
    momentoEmotivo: 5,
    notaPsicologica: "Grande voglia di riscatto dopo i fallimenti recenti nelle ultime edizioni mondiali.",
  },
  "Olanda": {
    motivazione: 88,
    pressione: 76,
    momentoEmotivo: 4,
    notaPsicologica: "Nazionale storicamente fortissima ma ancora senza titolo mondiale, con pressione piu gestibile.",
  },
  "Marocco": {
    motivazione: 88,
    pressione: 78,
    momentoEmotivo: 6,
    notaPsicologica: "Deve confermare il salto di status dopo il 2022; il caso Hakimi puo distrarre, ma il gruppo sembra solido.",
  },
  "Belgio": {
    motivazione: 84,
    pressione: 92,
    momentoEmotivo: -6,
    notaPsicologica: "Due pareggi e nessuna vittoria aumentano nettamente la pressione: l'ultima giornata diventa quasi uno spareggio.",
  },
  "Uruguay": {
    motivazione: 90,
    pressione: 84,
    momentoEmotivo: -4,
    notaPsicologica: "I due pareggi deludono e obbligano l'Uruguay a cercare il risultato contro la Spagna.",
  },
  "Croazia": {
    motivazione: 87,
    pressione: 68,
    momentoEmotivo: 4,
    notaPsicologica: "La vittoria corta con Panama riporta controllo emotivo dopo la sconfitta con l'Inghilterra, anche se la produzione resta da monitorare.",
  },
  "Messico": {
    motivazione: 93,
    pressione: 92,
    momentoEmotivo: 4,
    notaPsicologica: "Il Mondiale in casa alimenta entusiasmo e ambizione, ma rende ogni risultato un esame nazionale.",
  },
  "Corea del Sud": {
    motivazione: 86,
    pressione: 74,
    momentoEmotivo: 3,
    notaPsicologica: "Il gruppo esperto vuole regalarsi un ultimo percorso importante con una pressione gestibile.",
  },
  "Repubblica Ceca": {
    motivazione: 84,
    pressione: 62,
    momentoEmotivo: 1,
    notaPsicologica: "Squadra fisica con aspettative moderate: puo giocare con liberta e spirito da outsider.",
  },
  "Sudafrica": {
    motivazione: 90,
    pressione: 55,
    momentoEmotivo: 4,
    notaPsicologica: "Il ritorno sulla scena mondiale porta entusiasmo e fame, senza un peso mediatico eccessivo.",
  },
  "Canada": {
    motivazione: 92,
    pressione: 84,
    momentoEmotivo: 4,
    notaPsicologica: "Paese ospitante con una generazione ambiziosa: il pubblico aiuta, ma aumenta le aspettative.",
  },
  "Bosnia ed Erzegovina": {
    motivazione: 88,
    pressione: 58,
    momentoEmotivo: 3,
    notaPsicologica: "Il ritorno al Mondiale e un obiettivo storico che unisce il gruppo e riduce la paura di fallire.",
  },
  "Qatar": {
    motivazione: 82,
    pressione: 65,
    momentoEmotivo: -2,
    notaPsicologica: "Vuole migliorare l'esperienza del 2022, ma i risultati recenti hanno ridotto fiducia e certezze.",
  },
  "Svizzera": {
    motivazione: 85,
    pressione: 70,
    momentoEmotivo: 3,
    notaPsicologica: "Gruppo esperto e abituato ai tornei: aspettative concrete senza pressione da favorita.",
  },
  "Scozia": {
    motivazione: 89,
    pressione: 66,
    momentoEmotivo: 3,
    notaPsicologica: "Il ritorno al Mondiale genera entusiasmo enorme e una spinta collettiva superiore al peso delle attese.",
  },
  "Haiti": {
    motivazione: 97,
    pressione: 35,
    momentoEmotivo: 7,
    notaPsicologica: "Partecipazione dal valore storico: fame altissima e pochissima pressione sul risultato finale.",
  },
  "Stati Uniti": {
    motivazione: 93,
    pressione: 94,
    momentoEmotivo: 2,
    notaPsicologica: "Il torneo in casa e il progetto di crescita creano una spinta enorme, accompagnata da aspettative molto pesanti.",
  },
  "Turchia": {
    motivazione: 88,
    pressione: 78,
    momentoEmotivo: 3,
    notaPsicologica: "Generazione giovane e talentuosa, sostenuta da grande entusiasmo ma anche da un ambiente esigente.",
  },
  "Paraguay": {
    motivazione: 87,
    pressione: 64,
    momentoEmotivo: 4,
    notaPsicologica: "Il ritorno competitivo ha rafforzato identita e fiducia, con aspettative ancora equilibrate.",
  },
  "Australia": {
    motivazione: 86,
    pressione: 65,
    momentoEmotivo: 2,
    notaPsicologica: "Mentalita da torneo e spirito collettivo compensano una pressione esterna relativamente bassa.",
  },
  "Costa d'Avorio": {
    motivazione: 89,
    pressione: 68,
    momentoEmotivo: 5,
    notaPsicologica: "Gruppo fisico e fiducioso, spinto dall'ambizione di riportare una nazionale africana nelle fasi decisive.",
  },
  "Ecuador": {
    motivazione: 90,
    pressione: 66,
    momentoEmotivo: 3,
    notaPsicologica: "Generazione giovane e competitiva che sente possibile un percorso storico senza il peso delle favorite.",
  },
  "Curacao": {
    motivazione: 98,
    pressione: 30,
    momentoEmotivo: 8,
    notaPsicologica: "Esordio storico al Mondiale: entusiasmo massimo e aspettative esterne quasi inesistenti.",
  },
  "Svezia": {
    motivazione: 88,
    pressione: 70,
    momentoEmotivo: 5,
    notaPsicologica: "Il ritorno al torneo e la coppia offensiva di alto livello hanno aumentato fiducia e ambizione.",
  },
  "Giappone": {
    motivazione: 90,
    pressione: 68,
    momentoEmotivo: 5,
    notaPsicologica: "Il gruppo crede di poter superare finalmente gli ottavi, con fiducia costruita da risultati solidi.",
  },
  "Tunisia": {
    motivazione: 86,
    pressione: 60,
    momentoEmotivo: 1,
    notaPsicologica: "La qualificazione alimenta orgoglio e compattezza, mentre le aspettative restano contenute.",
  },
  "Egitto": {
    motivazione: 91,
    pressione: 78,
    momentoEmotivo: 7,
    notaPsicologica: "La rimonta sulla Nuova Zelanda e il primato nel gruppo rafforzano fiducia e leadership di Salah.",
  },
  "Iran": {
    motivazione: 87,
    pressione: 72,
    momentoEmotivo: 5,
    notaPsicologica: "Il punto conquistato contro il Belgio aumenta convinzione e compattezza in vista dello scontro con l'Egitto.",
  },
  "Nuova Zelanda": {
    motivazione: 95,
    pressione: 42,
    momentoEmotivo: -2,
    notaPsicologica: "Il buon avvio contro l'Egitto non basta: la rimonta subita riduce fiducia, pur senza creare grande pressione esterna.",
  },
  "Capo Verde": {
    motivazione: 97,
    pressione: 38,
    momentoEmotivo: 10,
    notaPsicologica: "Due pareggi contro Spagna e Uruguay alimentano entusiasmo massimo e la convinzione di poter superare il girone.",
  },
  "Arabia Saudita": {
    motivazione: 85,
    pressione: 70,
    momentoEmotivo: -5,
    notaPsicologica: "Il 4-0 subito dalla Spagna pesa sulla fiducia e aumenta l'urgenza di reagire nell'ultima partita del girone.",
  },
  "Norvegia": {
    motivazione: 92,
    pressione: 74,
    momentoEmotivo: 10,
    notaPsicologica: "Sei punti, sette gol segnati e qualificazione anticipata: entusiasmo massimo e crescente convinzione.",
  },
  "Senegal": {
    motivazione: 89,
    pressione: 79,
    momentoEmotivo: -7,
    notaPsicologica: "Due sconfitte nonostante quattro gol segnati aumentano frustrazione e pressione; la qualificazione e ora molto complicata.",
  },
  "Iraq": {
    motivazione: 91,
    pressione: 57,
    momentoEmotivo: -7,
    notaPsicologica: "Due sconfitte e sette reti subite riducono fiducia e margine, pur lasciando intatta la spinta della partecipazione storica.",
  },
  "Austria": {
    motivazione: 86,
    pressione: 67,
    momentoEmotivo: 2,
    notaPsicologica: "La sconfitta con l'Argentina ridimensiona l'entusiasmo dell'esordio, ma qualificazione e identita restano pienamente nelle sue mani.",
  },
  "Algeria": {
    motivazione: 88,
    pressione: 76,
    momentoEmotivo: 4,
    notaPsicologica: "La vittoria sulla Giordania cancella parte del peso dell'esordio e rimette qualificazione e fiducia nelle mani del gruppo.",
  },
  "Giordania": {
    motivazione: 97,
    pressione: 48,
    momentoEmotivo: -6,
    notaPsicologica: "Due sconfitte consecutive pesano sulla fiducia, anche se i gol segnati confermano capacita di competere e attaccare.",
  },
  "Colombia": {
    motivazione: 91,
    pressione: 74,
    momentoEmotivo: 8,
    notaPsicologica: "Due vittorie consecutive, inclusa la gara sporca col Congo, rafforzano fiducia, maturita e gestione dei momenti stretti.",
  },
  "RD Congo": {
    motivazione: 93,
    pressione: 54,
    momentoEmotivo: 1,
    notaPsicologica: "Il pari col Portogallo resta una spinta, ma la sconfitta corta con la Colombia frena l'entusiasmo senza svuotare il gruppo.",
  },
  "Uzbekistan": {
    motivazione: 96,
    pressione: 42,
    momentoEmotivo: -4,
    notaPsicologica: "La prima partecipazione resta storica, ma il 5-0 subito dal Portogallo pesa su fiducia e tenuta mentale.",
  },
  "Ghana": {
    motivazione: 90,
    pressione: 65,
    momentoEmotivo: 7,
    notaPsicologica: "Il punto contro l'Inghilterra aumenta fiducia e senso di solidita: il gruppo sente di poter reggere anche contro favorite vere.",
  },
  "Panama": {
    motivazione: 91,
    pressione: 58,
    momentoEmotivo: 0,
    notaPsicologica: "La sconfitta di misura con la Croazia lascia rammarico ma non abbatte il gruppo: resta una nazionale competitiva se la gara resta corta.",
  },
};

// Valori di partenza per la fase a eliminazione diretta. Il punteggio mostrato
// sul sito viene poi corretto (massimo +/- 5) dai risultati effettivi del girone.
const playoffMotivationProfiles = {
  "Argentina": { base: 95, tier: "maximum", reason: "campione in carica, ultima grande occasione per Messi" },
  "Francia": { base: 95, tier: "maximum", reason: "rosa da titolo e grande abitudine alle fasi finali" },
  "Brasile": { base: 95, tier: "maximum", reason: "pressione storica e obiettivo dichiarato: il titolo" },
  "Spagna": { base: 95, tier: "maximum", reason: "qualita da favorita, con attenzione alla disponibilita dei titolari" },
  "Portogallo": { base: 95, tier: "maximum", reason: "mai campione del mondo e possibile ultima occasione di Cristiano Ronaldo" },
  "Inghilterra": { base: 95, tier: "maximum", reason: "rosa forte, pressione alta e obiettivo minimo semifinale" },

  "Germania": { base: 91, tier: "very-high", reason: "grande bisogno di riscatto e ambizione da titolo" },
  "Olanda": { base: 91, tier: "very-high", reason: "talento, storia e desiderio di conquistare il primo Mondiale" },
  "Belgio": { base: 90, tier: "very-high", reason: "ultima finestra utile per una generazione di grande talento" },
  "Colombia": { base: 91, tier: "very-high", reason: "squadra ambiziosa e convinta di poter arrivare nelle fasi decisive" },
  "Croazia": { base: 90, tier: "very-high", reason: "esperienza nelle gare a eliminazione e forte identita competitiva" },
  "Messico": { base: 92, tier: "very-high", reason: "Mondiale in casa e enorme bisogno di superare il proprio limite storico" },

  "Marocco": { base: 86, tier: "high", reason: "semifinale 2022 da confermare e obiettivo quarti realistico" },
  "Svizzera": { base: 84, tier: "high", reason: "squadra solida, obiettivo quarti realistico e pressione controllata" },
  "Norvegia": { base: 86, tier: "high", reason: "generazione di talento che vede un percorso importante alla portata" },
  "Stati Uniti": { base: 87, tier: "high", reason: "torneo in casa e occasione decisiva per il progetto tecnico" },
  "Giappone": { base: 85, tier: "high", reason: "gruppo maturo che punta concretamente a superare gli ottavi" },
  "Egitto": { base: 84, tier: "high", reason: "leadership di Salah e traguardo dei quarti percepito come possibile" },

  "Sudafrica": { base: 80, tier: "nothing-to-lose", reason: "aspettative gia superate e liberta mentale da outsider" },
  "Capo Verde": { base: 82, tier: "nothing-to-lose", reason: "percorso storico e nessuna pressione sul risultato" },
  "Bosnia ed Erzegovina": { base: 80, tier: "nothing-to-lose", reason: "traguardo gia importante e possibilita di giocare senza paura" },
  "RD Congo": { base: 82, tier: "nothing-to-lose", reason: "entusiasmo collettivo e pochissimo da perdere" },
  "Ghana": { base: 81, tier: "nothing-to-lose", reason: "fiducia da outsider e capacita di alzare il livello contro le big" },
  "Senegal": { base: 83, tier: "nothing-to-lose", reason: "forza fisica, orgoglio e pressione inferiore alle favorite" },
  "Australia": { base: 79, tier: "nothing-to-lose", reason: "mentalita da torneo e aspettative gia superate" },
  "Canada": { base: 84, tier: "nothing-to-lose", reason: "pubblico di casa, generazione ambiziosa e occasione storica" },
  "Ecuador": { base: 82, tier: "nothing-to-lose", reason: "gioventu, intensita e prospettiva di un risultato storico" },
  "Svezia": { base: 80, tier: "nothing-to-lose", reason: "ritorno sul grande palcoscenico e attacco capace di sorprendere" },
};

// Eventi non deducibili dal tabellone possono essere aggiornati qui senza
// cambiare il motore. Ogni voce usa valori compresi fra -4 e +3.
const playoffMotivationEvents = {
  "Argentina": [{ value: 2, label: "ultima occasione per il leader simbolico Messi" }],
  "Portogallo": [{ value: 2, label: "ultima occasione per il leader simbolico Cristiano Ronaldo" }],
  "Messico": [{ value: 2, label: "paese ospitante ancora in corsa" }],
  "Stati Uniti": [{ value: 2, label: "paese ospitante ancora in corsa" }],
  "Canada": [{ value: 2, label: "paese ospitante ancora in corsa" }],
  "Capo Verde": [{ value: 3, label: "prima qualificazione alla fase playoff" }],
};
