const psychologicalFactors = {
  "Argentina": {
    motivazione: 92,
    pressione: 88,
    momentoEmotivo: 4,
    notaPsicologica: "Ultimo ciclo di diversi veterani e volonta di confermare il titolo del 2022.",
  },
  "Francia": {
    motivazione: 90,
    pressione: 85,
    momentoEmotivo: 2,
    notaPsicologica: "Nazionale abituata ad arrivare in fondo, con mentalita vincente e grandi aspettative.",
  },
  "Brasile": {
    motivazione: 95,
    pressione: 95,
    momentoEmotivo: -2,
    notaPsicologica: "Ossessione nazionale per il sesto Mondiale, ma ogni passo falso genera critiche enormi.",
  },
  "Inghilterra": {
    motivazione: 94,
    pressione: 98,
    momentoEmotivo: 3,
    notaPsicologica: "Generazione fortissima caricata dal peso storico del titolo che manca dal 1966.",
  },
  "Spagna": {
    motivazione: 89,
    pressione: 82,
    momentoEmotivo: 5,
    notaPsicologica: "Il 4-0 sull'Arabia Saudita cancella parte delle scorie dello 0-0 iniziale e restituisce fiducia alla nuova generazione.",
  },
  "Portogallo": {
    motivazione: 92,
    pressione: 92,
    momentoEmotivo: -1,
    notaPsicologica: "Probabile ultimo Mondiale di Cristiano Ronaldo: forte spinta emotiva, ma anche molte pressioni sulla sua gestione.",
  },
  "Germania": {
    motivazione: 91,
    pressione: 90,
    momentoEmotivo: 5,
    notaPsicologica: "Grande voglia di riscatto dopo i fallimenti recenti nelle ultime edizioni mondiali.",
  },
  "Olanda": {
    motivazione: 88,
    pressione: 76,
    momentoEmotivo: 4,
    notaPsicologica: "Nazionale storicamente fortissima ma ancora senza titolo mondiale, con pressione piu gestibile.",
  },
  "Marocco": {
    motivazione: 88,
    pressione: 78,
    momentoEmotivo: 6,
    notaPsicologica: "Deve confermare il salto di status dopo il 2022; il caso Hakimi puo distrarre, ma il gruppo sembra solido.",
  },
  "Belgio": {
    motivazione: 84,
    pressione: 92,
    momentoEmotivo: -6,
    notaPsicologica: "Due pareggi e nessuna vittoria aumentano nettamente la pressione: l'ultima giornata diventa quasi uno spareggio.",
  },
  "Uruguay": {
    motivazione: 90,
    pressione: 84,
    momentoEmotivo: -4,
    notaPsicologica: "I due pareggi deludono e obbligano l'Uruguay a cercare il risultato contro la Spagna.",
  },
  "Croazia": {
    motivazione: 87,
    pressione: 68,
    momentoEmotivo: 2,
    notaPsicologica: "Possibile fine ciclo di alcuni leader storici, ma con poca pressione rispetto ai risultati ottenuti.",
  },
  "Messico": {
    motivazione: 93,
    pressione: 92,
    momentoEmotivo: 4,
    notaPsicologica: "Il Mondiale in casa alimenta entusiasmo e ambizione, ma rende ogni risultato un esame nazionale.",
  },
  "Corea del Sud": {
    motivazione: 86,
    pressione: 74,
    momentoEmotivo: 3,
    notaPsicologica: "Il gruppo esperto vuole regalarsi un ultimo percorso importante con una pressione gestibile.",
  },
  "Repubblica Ceca": {
    motivazione: 84,
    pressione: 62,
    momentoEmotivo: 1,
    notaPsicologica: "Squadra fisica con aspettative moderate: puo giocare con liberta e spirito da outsider.",
  },
  "Sudafrica": {
    motivazione: 90,
    pressione: 55,
    momentoEmotivo: 4,
    notaPsicologica: "Il ritorno sulla scena mondiale porta entusiasmo e fame, senza un peso mediatico eccessivo.",
  },
  "Canada": {
    motivazione: 92,
    pressione: 84,
    momentoEmotivo: 4,
    notaPsicologica: "Paese ospitante con una generazione ambiziosa: il pubblico aiuta, ma aumenta le aspettative.",
  },
  "Bosnia ed Erzegovina": {
    motivazione: 88,
    pressione: 58,
    momentoEmotivo: 3,
    notaPsicologica: "Il ritorno al Mondiale e un obiettivo storico che unisce il gruppo e riduce la paura di fallire.",
  },
  "Qatar": {
    motivazione: 82,
    pressione: 65,
    momentoEmotivo: -2,
    notaPsicologica: "Vuole migliorare l'esperienza del 2022, ma i risultati recenti hanno ridotto fiducia e certezze.",
  },
  "Svizzera": {
    motivazione: 85,
    pressione: 70,
    momentoEmotivo: 3,
    notaPsicologica: "Gruppo esperto e abituato ai tornei: aspettative concrete senza pressione da favorita.",
  },
  "Scozia": {
    motivazione: 89,
    pressione: 66,
    momentoEmotivo: 3,
    notaPsicologica: "Il ritorno al Mondiale genera entusiasmo enorme e una spinta collettiva superiore al peso delle attese.",
  },
  "Haiti": {
    motivazione: 97,
    pressione: 35,
    momentoEmotivo: 7,
    notaPsicologica: "Partecipazione dal valore storico: fame altissima e pochissima pressione sul risultato finale.",
  },
  "Stati Uniti": {
    motivazione: 93,
    pressione: 94,
    momentoEmotivo: 2,
    notaPsicologica: "Il torneo in casa e il progetto di crescita creano una spinta enorme, accompagnata da aspettative molto pesanti.",
  },
  "Turchia": {
    motivazione: 88,
    pressione: 78,
    momentoEmotivo: 3,
    notaPsicologica: "Generazione giovane e talentuosa, sostenuta da grande entusiasmo ma anche da un ambiente esigente.",
  },
  "Paraguay": {
    motivazione: 87,
    pressione: 64,
    momentoEmotivo: 4,
    notaPsicologica: "Il ritorno competitivo ha rafforzato identita e fiducia, con aspettative ancora equilibrate.",
  },
  "Australia": {
    motivazione: 86,
    pressione: 65,
    momentoEmotivo: 2,
    notaPsicologica: "Mentalita da torneo e spirito collettivo compensano una pressione esterna relativamente bassa.",
  },
  "Costa d'Avorio": {
    motivazione: 89,
    pressione: 68,
    momentoEmotivo: 5,
    notaPsicologica: "Gruppo fisico e fiducioso, spinto dall'ambizione di riportare una nazionale africana nelle fasi decisive.",
  },
  "Ecuador": {
    motivazione: 90,
    pressione: 66,
    momentoEmotivo: 3,
    notaPsicologica: "Generazione giovane e competitiva che sente possibile un percorso storico senza il peso delle favorite.",
  },
  "Curacao": {
    motivazione: 98,
    pressione: 30,
    momentoEmotivo: 8,
    notaPsicologica: "Esordio storico al Mondiale: entusiasmo massimo e aspettative esterne quasi inesistenti.",
  },
  "Svezia": {
    motivazione: 88,
    pressione: 70,
    momentoEmotivo: 5,
    notaPsicologica: "Il ritorno al torneo e la coppia offensiva di alto livello hanno aumentato fiducia e ambizione.",
  },
  "Giappone": {
    motivazione: 90,
    pressione: 68,
    momentoEmotivo: 5,
    notaPsicologica: "Il gruppo crede di poter superare finalmente gli ottavi, con fiducia costruita da risultati solidi.",
  },
  "Tunisia": {
    motivazione: 86,
    pressione: 60,
    momentoEmotivo: 1,
    notaPsicologica: "La qualificazione alimenta orgoglio e compattezza, mentre le aspettative restano contenute.",
  },
  "Egitto": {
    motivazione: 91,
    pressione: 78,
    momentoEmotivo: 7,
    notaPsicologica: "La rimonta sulla Nuova Zelanda e il primato nel gruppo rafforzano fiducia e leadership di Salah.",
  },
  "Iran": {
    motivazione: 87,
    pressione: 72,
    momentoEmotivo: 5,
    notaPsicologica: "Il punto conquistato contro il Belgio aumenta convinzione e compattezza in vista dello scontro con l'Egitto.",
  },
  "Nuova Zelanda": {
    motivazione: 95,
    pressione: 42,
    momentoEmotivo: -2,
    notaPsicologica: "Il buon avvio contro l'Egitto non basta: la rimonta subita riduce fiducia, pur senza creare grande pressione esterna.",
  },
  "Capo Verde": {
    motivazione: 97,
    pressione: 38,
    momentoEmotivo: 10,
    notaPsicologica: "Due pareggi contro Spagna e Uruguay alimentano entusiasmo massimo e la convinzione di poter superare il girone.",
  },
  "Arabia Saudita": {
    motivazione: 85,
    pressione: 70,
    momentoEmotivo: -5,
    notaPsicologica: "Il 4-0 subito dalla Spagna pesa sulla fiducia e aumenta l'urgenza di reagire nell'ultima partita del girone.",
  },
  "Norvegia": {
    motivazione: 92,
    pressione: 74,
    momentoEmotivo: 5,
    notaPsicologica: "Il ritorno con una generazione guidata da Haaland e Odegaard produce entusiasmo e ambizioni elevate.",
  },
  "Senegal": {
    motivazione: 89,
    pressione: 72,
    momentoEmotivo: 2,
    notaPsicologica: "La nazionale vuole confermarsi tra le potenze africane, con un gruppo maturo e competitivo.",
  },
  "Iraq": {
    motivazione: 91,
    pressione: 57,
    momentoEmotivo: 4,
    notaPsicologica: "La partecipazione ha un grande valore nazionale e crea una spinta superiore alle pressioni sul risultato.",
  },
  "Austria": {
    motivazione: 86,
    pressione: 67,
    momentoEmotivo: 3,
    notaPsicologica: "Il progetto tecnico ha dato identita e fiducia, con aspettative positive ma ancora sostenibili.",
  },
  "Algeria": {
    motivazione: 88,
    pressione: 68,
    momentoEmotivo: 3,
    notaPsicologica: "Il ritorno al Mondiale alimenta orgoglio e desiderio di riscatto dopo anni di assenza.",
  },
  "Giordania": {
    motivazione: 97,
    pressione: 40,
    momentoEmotivo: 8,
    notaPsicologica: "Esordio mondiale storico: entusiasmo altissimo e totale liberta dal peso delle aspettative.",
  },
  "Colombia": {
    motivazione: 91,
    pressione: 74,
    momentoEmotivo: 5,
    notaPsicologica: "La crescita recente e una generazione offensiva matura hanno alzato fiducia e ambizione.",
  },
  "RD Congo": {
    motivazione: 93,
    pressione: 54,
    momentoEmotivo: 6,
    notaPsicologica: "Il ritorno al Mondiale ha un valore storico e unisce un gruppo che puo giocare senza paura.",
  },
  "Uzbekistan": {
    motivazione: 96,
    pressione: 42,
    momentoEmotivo: 7,
    notaPsicologica: "Prima partecipazione mondiale: fame enorme, entusiasmo diffuso e pressione competitiva limitata.",
  },
  "Ghana": {
    motivazione: 90,
    pressione: 65,
    momentoEmotivo: 4,
    notaPsicologica: "Tradizione mondiale e nuova energia generazionale alimentano una forte voglia di riscatto.",
  },
  "Panama": {
    motivazione: 91,
    pressione: 58,
    momentoEmotivo: 5,
    notaPsicologica: "La crescita nella CONCACAF ha aumentato fiducia e ambizione, senza creare pressioni eccessive.",
  },
};
