const tournamentScorersAll = [
  { player: "Kylian Mbappe", team: "Francia", goals: 7, penalties: 1 },
  { player: "Lionel Messi", team: "Argentina", goals: 7, penalties: 0 },
  { player: "Harry Kane", team: "Inghilterra", goals: 6, penalties: 2 },
  { player: "Erling Haaland", team: "Norvegia", goals: 7, penalties: 0 },
  { player: "Vinicius Jr", team: "Brasile", goals: 4, penalties: 0 },
  { player: "Ousmane Dembele", team: "Francia", goals: 4, penalties: 0 },
  { player: "Ismaila Sarr", team: "Senegal", goals: 4, penalties: 0 },
  { player: "Mikel Oyarzabal", team: "Spagna", goals: 4, penalties: 0 },
  { player: "Cristiano Ronaldo", team: "Portogallo", goals: 3, penalties: 1 },
  { player: "Yoane Wissa", team: "RD Congo", goals: 3, penalties: 1 },
  { player: "Kai Havertz", team: "Germania", goals: 3, penalties: 1 },
  { player: "Johan Manzambi", team: "Svizzera", goals: 3, penalties: 0 },
  { player: "Jonathan David", team: "Canada", goals: 3, penalties: 0 },
  { player: "Ismael Saibari", team: "Marocco", goals: 3, penalties: 0 },
  { player: "Deniz Undav", team: "Germania", goals: 3, penalties: 0 },
  { player: "Cody Gakpo", team: "Olanda", goals: 3, penalties: 0 },
  { player: "Folarin Balogun", team: "Stati Uniti", goals: 3, penalties: 0 },
  { player: "Matheus Cunha", team: "Brasile", goals: 3, penalties: 0 },
  { player: "Julian Quinones", team: "Messico", goals: 4, penalties: 0 },
  { player: "Elijah Just", team: "Nuova Zelanda", goals: 3, penalties: 0 },
  { player: "Breel Embolo", team: "Svizzera", goals: 2, penalties: 1 },
  { player: "Marco Arnautovic", team: "Austria", goals: 2, penalties: 1 },
  { player: "Youri Tielemans", team: "Belgio", goals: 2, penalties: 1 },
  { player: "Romelu Lukaku", team: "Belgio", goals: 2, penalties: 0 },
  { player: "Emam Ashour", team: "Egitto", goals: 2, penalties: 0 },
  { player: "Azzedine Ounahi", team: "Marocco", goals: 2, penalties: 0 },
  { player: "Ruben Vargas", team: "Svizzera", goals: 2, penalties: 0 },
  { player: "Amad Diallo", team: "Costa d'Avorio", goals: 2, penalties: 0 },
  { player: "Ermin Mahmic", team: "Bosnia ed Erzegovina", goals: 2, penalties: 0 },
  { player: "Nicolas Pepe", team: "Costa d'Avorio", goals: 2, penalties: 0 },
  { player: "Pape Gueye", team: "Senegal", goals: 2, penalties: 0 },
  { player: "Habib Diarra", team: "Senegal", goals: 2, penalties: 0 },
  { player: "Maxi Araujo", team: "Uruguay", goals: 2, penalties: 0 },
  { player: "Daichi Kamada", team: "Giappone", goals: 2, penalties: 0 },
  { player: "Leandro Trossard", team: "Belgio", goals: 2, penalties: 0 },
  { player: "Bradley Barcola", team: "Francia", goals: 2, penalties: 0 },
  { player: "Jude Bellingham", team: "Inghilterra", goals: 4, penalties: 0 },
  { player: "Daniel Munoz", team: "Colombia", goals: 2, penalties: 0 },
  { player: "Ramin Rezaeian", team: "Iran", goals: 2, penalties: 0 },
  { player: "Crysencio Summerville", team: "Olanda", goals: 2, penalties: 0 },
  { player: "Ayase Ueda", team: "Giappone", goals: 2, penalties: 0 },
  { player: "Riyad Mahrez", team: "Algeria", goals: 2, penalties: 0 },
  { player: "Soufiane Rahimi", team: "Marocco", goals: 2, penalties: 0 },
  { player: "Raul Jimenez", team: "Messico", goals: 3, penalties: 1 },
  { player: "Cyle Larin", team: "Canada", goals: 2, penalties: 0 },
  { player: "Anthony Elanga", team: "Svezia", goals: 2, penalties: 0 },
  { player: "Yasin Ayari", team: "Svezia", goals: 2, penalties: 0 },
];

const tournamentScorerActiveTeams = new Set([
  "Argentina", "Belgio", "Colombia", "Egitto", "Francia", "Inghilterra",
  "Marocco", "Norvegia", "Portogallo", "Spagna", "Stati Uniti", "Svizzera",
]);

const tournamentScorers = tournamentScorersAll.filter((entry) =>
  tournamentScorerActiveTeams.has(entry.team)
);

const tournamentScorersMeta = {
  updated: "2026-07-06",
  source: "Diretta.it",
  url: "https://www.diretta.it/partita/calcio/brasile-I9l9aqLq/norvegia-8rP6JO0H/?mid=tpOhKWcC",
  scope: "Giocatori con almeno 2 gol",
};
